# Generated by Django 3.0.4 on 2020-04-26 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lost_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150, verbose_name='location')),
                ('city', models.CharField(max_length=60, verbose_name='city')),
                ('state', models.CharField(max_length=60, verbose_name='state')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('lost_date', models.DateField(verbose_name='lost date')),
                ('reported_date', models.DateField(auto_now_add=True, verbose_name='date reported')),
                ('desc', models.CharField(max_length=255, verbose_name='desc')),
                ('img', models.ImageField(upload_to='lost_persons')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='findmatch.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lost_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150, verbose_name='location')),
                ('city', models.CharField(max_length=60, verbose_name='city')),
                ('state', models.CharField(max_length=60, verbose_name='state')),
                ('lost_date', models.DateField(verbose_name='lost date')),
                ('reported_date', models.DateField(auto_now_add=True, verbose_name='date reported')),
                ('desc', models.CharField(max_length=255, verbose_name='desc')),
                ('img', models.ImageField(upload_to='lost_items')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='findmatch.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Found_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150, verbose_name='location')),
                ('city', models.CharField(max_length=60, verbose_name='city')),
                ('state', models.CharField(max_length=60, verbose_name='state')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('found_date', models.DateField(verbose_name='found date')),
                ('reported_date', models.DateField(auto_now_add=True, verbose_name='date reported')),
                ('desc', models.CharField(max_length=255, verbose_name='desc')),
                ('img', models.ImageField(upload_to='found_persons')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='findmatch.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Found_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150, verbose_name='location')),
                ('city', models.CharField(max_length=60, verbose_name='city')),
                ('state', models.CharField(max_length=60, verbose_name='state')),
                ('found_date', models.DateField(verbose_name='found date')),
                ('reported_date', models.DateField(auto_now_add=True, verbose_name='date reported')),
                ('desc', models.CharField(max_length=255, verbose_name='desc')),
                ('img', models.ImageField(upload_to='found_items')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='findmatch.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
