# Generated by Django 3.0.4 on 2020-05-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='found_item',
            name='report',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='found_person',
            name='report',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lost_item',
            name='report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lost_person',
            name='report',
            field=models.BooleanField(default=False),
        ),
    ]
