# Generated by Django 3.0.4 on 2020-04-24 11:06

from django.db import migrations, models
import match.models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20200424_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found_item',
            name='img',
            field=models.ImageField(upload_to=match.models.UploadToPathAndRename('C:\\Users\\Stuti\\project_landf\\LostAndFound\\media\\found_item')),
        ),
        migrations.AlterField(
            model_name='found_person',
            name='img',
            field=models.ImageField(upload_to=match.models.UploadToPathAndRename('C:\\Users\\Stuti\\project_landf\\LostAndFound\\media\\found_person')),
        ),
        migrations.AlterField(
            model_name='lost_item',
            name='img',
            field=models.ImageField(upload_to=match.models.UploadToPathAndRename('C:\\Users\\Stuti\\project_landf\\LostAndFound\\media\\lost_item')),
        ),
        migrations.AlterField(
            model_name='lost_person',
            name='img',
            field=models.ImageField(upload_to=match.models.UploadToPathAndRename('C:\\Users\\Stuti\\project_landf\\LostAndFound\\media\\lost_person')),
        ),
    ]
